In [29]:
import requests
import pandas as pd
import time
import json
from datetime import date,timedelta

In [30]:
#Declare file config
file_path = '../credentials/config.json'

#Open and read Json file
with open(file_path, "r") as file:
    config_data = json.load(file)

In [31]:
current_date = date.today()
current_date = current_date.strftime('%d/%m/%Y')
print("Current Date:", current_date)

Current Date: 23/10/2025

In [32]:
url = "https://fc-data.ssi.com.vn/api/v2/Market/AccessToken"

payload = {
    "consumerID": config_data["consumerID"],
    "consumerSecret": config_data["consumerSecret"]
}

headers = {
    "Content-Type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)
if response.status_code == 200:
    access_token = response.json()['data'].get("accessToken")
else:
    print("Failed to get access token. Status Code:", response.status_code)
    print("Response Body:", response.text)
    exit()

In [33]:
start_date = (date.today() - timedelta(days = 0)).strftime('%d/%m/%Y')
end_date = (date.today() - timedelta(days = 0)).strftime('%d/%m/%Y')

In [34]:
# Replace with the token you obtained
url = "https://fc-data.ssi.com.vn/api/v2/Market/DailyStockPrice"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}
df = pd.DataFrame()
for index in range(1,2):
    params = {
        # "symbol": 'SSI',
        "fromDate": start_date,
        "toDate": end_date,
        "pageIndex": index,
        "pageSize": 1000,
        # "market" : 'HNX'
    }

    # Send the GET request
    response = requests.get(url, headers=headers,params=params)
    data = response.json()['data']
    df_response = pd.DataFrame(data)
    df = pd.concat([df, df_response], ignore_index=True)
    time.sleep(1)
    if len(df_response) == 0:
        break

In [35]:
print(df)

     TradingDate PriceChange PerPriceChange CeilingPrice   FloorPrice  \
0     23/10/2025           0              0            0  10946161920
1     23/10/2025       18.60         0.9690      2054.80         1786
2     23/10/2025       28.50         1.5620      1952.10      1696.70
3     23/10/2025       11.60         0.6290      1972.50      1714.50
4     23/10/2025       17.50         0.9090      2060.80      1791.20
...          ...         ...            ...          ...          ...
4237  23/10/2025           0              0   9091277300  12617134570
4238  23/10/2025           0              0   9091277300   1429476330
4239  23/10/2025           0              0   9091277300    933358570
4240  23/10/2025           0              0   9091277300   8776712160
4241  23/10/2025           0              0            0  10938161920

         RefPrice   OpenPrice HighestPrice LowestPrice  ClosePrice  ...  \
0      5473080960     6553600      2312000           0     2312000  ...
1         1920.40     1915.70      1954.90     1910.80        1939  ...
2         1824.40        1835      1852.90        1835     1852.90  ...
3         1843.50        1855         1865     1837.10     1855.10  ...
4            1926        1924         1959        1913     1943.50  ...
...           ...         ...          ...         ...         ...  ...
4237  10854205935  5389762880   8053064000   163921920  8053064000  ...
4238   5260376815  5389762880   8053064000    40714240  8053064000  ...
4239   5012317935  5389762880   8053064000   600391680  8053064000  ...
4240   8933994730  5389762880   8053064000    12533760  8053064000  ...
4241   5469080960     6553600       307520           0      307520  ...

     TotalBuyTrade TotalBuyTradeVol TotalSellTrade TotalSellTradeVol  \
0                0                0              0                 0
1                0                0              0                 0
2                0                0              0                 0
3                0                0              0                 0
4                0                0              0                 0
...            ...              ...            ...               ...
4237             0                0              0                 0
4238             0                0              0                 0
4239             0                0              0                 0
4240             0                0              0                 0
4241             0                0              0                 0

     NetBuySellVol NetBuySellVal TotalTradedVol TotalTradedValue     Symbol  \
0                0             0              0                0    0.8536:
1              150   28965670000            704     136085790000  VN30F2512
2                0             0             17       3130820000  41I2FC000
3                2     371020000            275      50987380000  41I2FB000
4             1270  248160380000         364965   70678202250000  41I1FB000
...            ...           ...            ...              ...        ...
4237             0             0              0                0   02006222
4238             0             0              0                0   02006172
4239             0             0              0                0   02006152
4240             0             0              0                0   02006052
4241             0             0              0                0    0.9667:

      Time
0     None
1     None
2     None
3     None
4     None
...    ...
4237  None
4238  None
4239  None
4240  None
4241  None

[4242 rows x 31 columns]

In [36]:
df_sort = df.sort_values(by=['Symbol'])
display(df_sort)

,TradingDate,PriceChange,PerPriceChange,CeilingPrice,FloorPrice,RefPrice,OpenPrice,HighestPrice,LowestPrice,ClosePrice,...,TotalBuyTrade,TotalBuyTradeVol,TotalSellTrade,TotalSellTradeVol,NetBuySellVol,NetBuySellVal,TotalTradedVol,TotalTradedValue,Symbol,Time
0,23/10/2025,0,0,0,10946161920,5473080960,6553600,2312000,0,2312000,...,0,0,0,0,0,0,0,0,0.8536:,None
4241,23/10/2025,0,0,0,10938161920,5469080960,6553600,307520,0,307520,...,0,0,0,0,0,0,0,0,0.9667:,None
4240,23/10/2025,0,0,9091277300,8776712160,8933994730,5389762880,8053064000,12533760,8053064000,...,0,0,0,0,0,0,0,0,02006052,None
4239,23/10/2025,0,0,9091277300,933358570,5012317935,5389762880,8053064000,600391680,8053064000,...,0,0,0,0,0,0,0,0,02006152,None
4238,23/10/2025,0,0,9091277300,1429476330,5260376815,5389762880,8053064000,40714240,8053064000,...,0,0,0,0,0,0,0,0,02006172,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,23/10/2025,-50,-0.40,15200,13300,14250,14200,14200,13700,14200,...,0,0,0,0,0,0,800,11310000,YBM,None
8,23/10/2025,-100,-0.80,13350,11650,12500,12450,12600,12300,12400,...,0,0,0,0,1170300,14370795000,2081200,25715480000,YEG,None
7,23/10/2025,0,0,8800,3800,6300,6300,6300,6300,6300,...,0,0,0,0,0,0,0,0,YRC,None
6,23/10/2025,0,0,0,0,0,6300,6300,6300,0,...,0,0,0,0,0,0,0,0,YSC,None
5,23/10/2025,0,0,34500,25500,30000,34000,34000,34000,34000,...,0,0,0,0,0,0,0,0,YTC,None

In [37]:
df = df.drop_duplicates()

In [38]:
display(df)

,TradingDate,PriceChange,PerPriceChange,CeilingPrice,FloorPrice,RefPrice,OpenPrice,HighestPrice,LowestPrice,ClosePrice,...,TotalBuyTrade,TotalBuyTradeVol,TotalSellTrade,TotalSellTradeVol,NetBuySellVol,NetBuySellVal,TotalTradedVol,TotalTradedValue,Symbol,Time
0,23/10/2025,0,0,0,10946161920,5473080960,6553600,2312000,0,2312000,...,0,0,0,0,0,0,0,0,0.8536:,None
1,23/10/2025,18.60,0.9690,2054.80,1786,1920.40,1915.70,1954.90,1910.80,1939,...,0,0,0,0,150,28965670000,704,136085790000,VN30F2512,None
2,23/10/2025,28.50,1.5620,1952.10,1696.70,1824.40,1835,1852.90,1835,1852.90,...,0,0,0,0,0,0,17,3130820000,41I2FC000,None
3,23/10/2025,11.60,0.6290,1972.50,1714.50,1843.50,1855,1865,1837.10,1855.10,...,0,0,0,0,2,371020000,275,50987380000,41I2FB000,None
4,23/10/2025,17.50,0.9090,2060.80,1791.20,1926,1924,1959,1913,1943.50,...,0,0,0,0,1270,248160380000,364965,70678202250000,41I1FB000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4237,23/10/2025,0,0,9091277300,12617134570,10854205935,5389762880,8053064000,163921920,8053064000,...,0,0,0,0,0,0,0,0,02006222,None
4238,23/10/2025,0,0,9091277300,1429476330,5260376815,5389762880,8053064000,40714240,8053064000,...,0,0,0,0,0,0,0,0,02006172,None
4239,23/10/2025,0,0,9091277300,933358570,5012317935,5389762880,8053064000,600391680,8053064000,...,0,0,0,0,0,0,0,0,02006152,None
4240,23/10/2025,0,0,9091277300,8776712160,8933994730,5389762880,8053064000,12533760,8053064000,...,0,0,0,0,0,0,0,0,02006052,None
4241,23/10/2025,0,0,0,10938161920,5469080960,6553600,307520,0,307520,...,0,0,0,0,0,0,0,0,0.9667:,None